#
# /etc/pacman.conf used inside the build chroot.
# Adds the local TorrentOS repo (./repo/) ahead of the upstream mirrors
# so torrentos-* packages resolve from our own builds.
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
ParallelDownloads = 8

[torrentos]
SigLevel = Optional TrustAll
Server = file:///$repo

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
